const routes = {
  '/': 'Home',
  '/dashboard': 'Dashboard',
  '/components': 'Components',
  '/charts': 'Charts',
  '/components/alerts': 'Alerts',
  '/components/badges': 'Badges',
  '/components/buttons': 'Buttons',
  '/components/button-groups': 'Button Groups',
  '/components/breadcrumbs': 'Breadcrumbs',
  '/components/cards': 'Cards',
  '/components/carousels': 'Carousels',
  '/components/dropdowns': 'Dropdowns',
  '/components/forms': 'Forms',
  '/components/input-groups': 'Input Groups',
  '/components/list-groups': 'List Groups',
  '/components/jumbotrons': 'Jumbotrons',
  '/components/modals': 'Modals',
  '/components/navs': 'Navs',
  '/components/navbars': 'Navbars',
  '/components/paginations': 'Paginations',
  '/components/popovers': 'Popovers',
  '/components/progress-bars': 'Progress Bars',
  '/components/social-buttons': 'Social Buttons',
  '/components/switches': 'Switches',
  '/components/tables': 'Tables',
  '/components/tabs': 'Tabs',
  '/components/tooltips': 'Tooltips',

  '/icons': 'Icons',
  '/icons/font-awesome': 'Font Awesome',
  '/icons/simple-line-icons': 'Simple Line Icons',
  '/widgets': 'Widgets'
};
export default routes;
